-- Run this in Supabase to support stricter leaderboard anti-spam checks.
-- The API also creates these tables automatically when the DB user is allowed
-- to run DDL, but keeping this migration makes the schema explicit.

create table if not exists public.game_sessions (
  sid text primary key,
  issued_at timestamptz not null,
  issued_ip text,
  used_at timestamptz,
  used_ip text
);

create table if not exists public.score_attempts (
  id bigint generated by default as identity primary key,
  ip text not null,
  name text not null,
  normalized_name text not null,
  created_at timestamptz not null default now()
);

create index if not exists score_attempts_ip_created_at_idx
  on public.score_attempts (ip, created_at desc);

create index if not exists score_attempts_name_created_at_idx
  on public.score_attempts (normalized_name, created_at desc);

alter table public.game_sessions enable row level security;
alter table public.score_attempts enable row level security;

revoke all on table public.game_sessions from anon;
revoke all on table public.game_sessions from authenticated;
revoke all on table public.score_attempts from anon;
revoke all on table public.score_attempts from authenticated;
