-- Run this in the Supabase SQL editor for the project used by Cookie Crumbler.
-- It removes injected/invalid rows, validates future rows at the database layer,
-- and blocks direct public table access so writes must go through the Vercel API.

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null,
  clicks integer not null,
  time_ms integer not null,
  created_at timestamptz not null default now()
);

delete from public.scores
where name is null
   or name !~ '^[A-Z0-9 _.-]{1,8}$'
   or name ~ '[<>]'
   or clicks is null
   or clicks < 1
   or clicks > 5000
   or time_ms is null
   or time_ms < 1000
   or time_ms > 600000
   or clicks / (time_ms::numeric / 1000) > 30;

alter table public.scores enable row level security;

do $$
declare
  policy_row record;
begin
  for policy_row in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'scores'
  loop
    execute format('drop policy if exists %I on public.scores', policy_row.policyname);
  end loop;
end $$;

revoke all on table public.scores from anon;
revoke all on table public.scores from authenticated;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'scores_name_format_check'
  ) then
    alter table public.scores
      add constraint scores_name_format_check
      check (name ~ '^[A-Z0-9 _.-]{1,8}$' and name !~ '[<>]');
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'scores_clicks_range_check'
  ) then
    alter table public.scores
      add constraint scores_clicks_range_check
      check (clicks between 1 and 5000);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'scores_time_ms_range_check'
  ) then
    alter table public.scores
      add constraint scores_time_ms_range_check
      check (time_ms between 1000 and 600000);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'scores_realistic_rate_check'
  ) then
    alter table public.scores
      add constraint scores_realistic_rate_check
      check (clicks / (time_ms::numeric / 1000) <= 30);
  end if;
end $$;
